import {saveImage} from './save-image.js';
import {SoftwareRenderer} from './software-renderer.js';
import {Scene,PerspectiveCamera,WebGLRenderer,AmbientLight,DirectionalLight,Group,CanvasTexture,SRGBColorSpace,MeshBasicMaterial,Raycaster,Vector2,Box3,Vector3} from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {restoreRig,CHANNELS} from './model.js';
const $=id=>document.getElementById(id);
const viewport=$('viewport'),picker=$('photos'),status=$('status');
const ratios=[16/9,2/3,16/9,16/9,3/5,3/4,3/4,2/3];
let renderer,scene,camera,controls,rig,model,screenMeshes=[],textures=[],images=Array(8).fill(null),pool=[],target=0,busy=false,outputData='',previousFocus=null,frame=0;
const reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const buttons=CHANNELS.map((name,i)=>{const b=document.createElement('button');b.className='channel';b.type='button';b.textContent=String(i+1).padStart(2,'0');b.setAttribute('aria-label','屏幕 '+(i+1)+'，上传照片');b.addEventListener('click',()=>choose(i));$('channels').appendChild(b);return b;});
function announce(text){status.textContent=text;}
function choose(index){if(busy)return;target=index;buttons.forEach((b,i)=>b.classList.toggle('selected',i===index));picker.value='';picker.click();}
function canvasFor(index,photo){
 const c=document.createElement('canvas');c.width=Math.round(768*Math.min(ratios[index],1));c.height=Math.round(c.width/ratios[index]);const x=c.getContext('2d');
 if(photo){const scale=Math.max(c.width/photo.width,c.height/photo.height);x.drawImage(photo,(c.width-photo.width*scale)/2,(c.height-photo.height*scale)/2,photo.width*scale,photo.height*scale);}
 else{const w=c.width,h=c.height;x.fillStyle='#14241e';x.fillRect(0,0,w,h);x.strokeStyle='#345246';x.lineWidth=1;for(let n=0;n<w;n+=32){x.beginPath();x.moveTo(n,0);x.lineTo(n,h);x.stroke();}for(let n=0;n<h;n+=32){x.beginPath();x.moveTo(0,n);x.lineTo(w,n);x.stroke();}x.fillStyle='#b8cc88';x.font='24px monospace';x.fillText('CH / '+String(index+1).padStart(2,'0'),25,43);x.strokeStyle='#efffa8';x.lineWidth=2;x.beginPath();x.moveTo(w/2-23,h/2);x.lineTo(w/2+23,h/2);x.moveTo(w/2,h/2-23);x.lineTo(w/2,h/2+23);x.stroke();x.font='18px monospace';x.textAlign='center';x.fillText('ADD PHOTO',w/2,h-32);}
 return c;
}
function updateScreens(){
 images.forEach((img,i)=>{const c=canvasFor(i,img);if(screenMeshes[i]){if(textures[i])textures[i].dispose();const texture=new CanvasTexture(c);texture.flipY=false;texture.colorSpace=SRGBColorSpace;textures[i]=texture;screenMeshes[i].material.map=texture;screenMeshes[i].material.needsUpdate=true;}buttons[i].classList.toggle('filled',!!img);buttons[i].setAttribute('aria-label','屏幕 '+(i+1)+(img?'，替换照片':'，上传照片'));});
 $('count').textContent=String(images.filter(Boolean).length).padStart(2,'0')+' / 08 PHOTOS';
 outputData='';if(!renderer)renderFallback();draw();
}
function renderFallback(){const holder=$('fallback');holder.hidden=false;holder.textContent='';images.forEach((photo,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label','屏幕 '+(i+1)+'，上传照片');const img=document.createElement('img');img.src=canvasFor(i,photo).toDataURL('image/jpeg',.8);img.alt='屏幕 '+(i+1);b.appendChild(img);b.addEventListener('click',()=>choose(i));holder.appendChild(b);});}
function draw(){if(renderer&&scene)renderer.render(scene,camera);}
function fitCamera(aspect){const v=aspect<.85?1.14:1.05;const size=new Box3().setFromObject(rig).getSize(new Vector3());const distance=Math.max(size.y/(2*Math.tan(Math.PI*40/360)),size.x/(2*Math.tan(Math.PI*40/360)*aspect))*v;camera.position.set(0,.12,distance+size.z*.35);camera.lookAt(0,0,0);camera.updateProjectionMatrix();}
function resize(){if(!renderer)return;const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;fitCamera(camera.aspect);controls.update();draw();}
function resetView(){if(!rig)return;rig.rotation.set(.02,Math.PI,0);controls.target.set(0,0,0);resize();outputData='';}
function init(){
 try{try{renderer=new WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true,powerPreference:'default'});}catch(webglError){renderer=new SoftwareRenderer();}renderer.setPixelRatio(renderer.isSoftwareRenderer?1:Math.min(window.devicePixelRatio||1,1.65));renderer.outputColorSpace=SRGBColorSpace;viewport.appendChild(renderer.domElement);
 scene=new Scene();camera=new PerspectiveCamera(40,1,.1,100);scene.add(new AmbientLight('#e7edf2',1.35));[[5,8,9,2.8,'#ffffff'],[-8,2,5,1.8,'#b8c9d8'],[1,-7,-4,2,'#f4f7fa']].forEach(a=>{const l=new DirectionalLight(a[4],a[3]);l.position.set(a[0],a[1],a[2]);scene.add(l);});
 model=restoreRig();rig=new Group();rig.add(model);rig.rotation.set(.02,Math.PI,0);scene.add(rig);const center=new Box3().setFromObject(rig).getCenter(new Vector3());rig.position.sub(center);
 screenMeshes=CHANNELS.map(name=>{const mesh=model.getObjectByName(name+'_project_photo');mesh.material=new MeshBasicMaterial({toneMapped:false});return mesh;});
 controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableZoom=false;controls.enableDamping=false;controls.minPolarAngle=Math.PI*.30;controls.maxPolarAngle=Math.PI*.70;controls.rotateSpeed=.55;controls.addEventListener('change',()=>{outputData='';cancelAnimationFrame(frame);frame=requestAnimationFrame(draw);});
 let down=null;renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};});
 renderer.domElement.addEventListener('pointerup',e=>{if(!down)return;const delta=Math.hypot(e.clientX-down.x,e.clientY-down.y);down=null;if(delta>7)return;const r=renderer.domElement.getBoundingClientRect();const ray=new Raycaster();ray.setFromCamera(new Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hits=ray.intersectObjects(model.children,true).filter(h=>h.object.visible&&!h.object.name.includes('acrylic')&&!h.object.name.includes('clear'));if(!hits.length)return;let o=hits[0].object;while(o){const i=CHANNELS.indexOf(o.name);if(i>=0){choose(i);return;}o=o.parent;}});
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(frame);viewport.hidden=true;renderer=null;renderFallback();announce('3D 暂不可用，已切换平面模式，照片仍可编辑和保存');});
 window.addEventListener('resize',resize);resize();updateScreens();
 }catch(error){console.error('Signal Rig initialization failed:',error);if(renderer)renderer.dispose();renderer=null;viewport.hidden=true;renderFallback();announce('当前设备使用平面模式 · 点击屏幕放入照片');}
}
function decode(file){return new Promise((resolve,reject)=>{if(!/^image\//.test(file.type)&&!(/\.(jpe?g|png|webp|gif|heic|avif)$/i.test(file.name)))return reject(new Error('请选择图片文件'));if(file.size>25*1024*1024)return reject(new Error('单张图片请小于 25MB'));const reader=new FileReader();reader.onerror=()=>reject(new Error('照片读取失败'));reader.onload=()=>{const im=new Image();im.onerror=()=>reject(new Error('无法读取这张照片，请尝试 JPG 或 PNG'));im.onload=()=>{try{const c=document.createElement('canvas');const scale=Math.min(1,1280/Math.max(im.naturalWidth,im.naturalHeight));c.width=Math.max(1,Math.round(im.naturalWidth*scale));c.height=Math.max(1,Math.round(im.naturalHeight*scale));c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c);}catch(e){reject(new Error('照片太大，无法处理'));}};im.src=reader.result;};reader.readAsDataURL(file);});}
function busyState(on){busy=on;['shuffle','build','save','save-output'].forEach(id=>$(id).disabled=on);buttons.forEach(b=>b.disabled=on);}
picker.addEventListener('change',async()=>{const files=Array.from(picker.files||[]).slice(0,8);if(!files.length)return;busyState(true);announce('正在把照片接入装置…');const loaded=[],errors=[];for(const file of files){try{loaded.push(await decode(file));}catch(e){errors.push(e.message);}}
 if(loaded.length){if(loaded.length===1&&pool.length){images[target]=loaded[0];pool=Array.from(new Set(images.filter(Boolean)));}
 else{pool=loaded;const remaining=loaded.slice();images=Array(8).fill(null);images[target]=remaining.shift();const indexes=Array.from({length:8},(_,i)=>i).filter(i=>i!==target);for(const i of indexes){if(remaining.length){let best=0;remaining.forEach((im,j)=>{if(Math.abs(Math.log((im.width/im.height)/ratios[i]))<Math.abs(Math.log((remaining[best].width/remaining[best].height)/ratios[i])))best=j;});images[i]=remaining.splice(best,1)[0];}else images[i]=pool[i%pool.length];}}
 updateScreens();announce(errors.length?'已接入 '+loaded.length+' 张；'+errors[0]:('已接入 '+loaded.length+' 张照片 · 可拖动、打乱或生成图片'));}
 else announce(errors[0]||'未能读取照片');busyState(false);});
$('shuffle').addEventListener('click',()=>{if(!pool.length){choose(0);return;}const prev=images.slice();for(let i=images.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));const tmp=images[i];images[i]=images[j];images[j]=tmp;}if(images.every((im,i)=>im===prev[i]))images.push(images.shift());updateScreens();announce(pool.length===1?'只有一张照片，添加更多照片后可以打乱':'照片已重新分配 · 屏幕位置保持不变');});
$('reset-view').addEventListener('click',resetView);
function poster(){
 const c=document.createElement('canvas');c.width=1200;c.height=1600;const x=c.getContext('2d');x.fillStyle='#1e2522';x.fillRect(0,0,1200,1600);x.strokeStyle='rgba(170,195,170,.065)';for(let n=0;n<1600;n+=40){x.beginPath();x.moveTo(0,n);x.lineTo(1200,n);x.stroke();x.beginPath();x.moveTo(n,0);x.lineTo(n,1600);x.stroke();}const g=x.createRadialGradient(600,730,0,600,730,670);g.addColorStop(0,'rgba(74,96,77,.3)');g.addColorStop(1,'rgba(30,37,34,0)');x.fillStyle=g;x.fillRect(0,0,1200,1600);
 x.fillStyle='#f9ff4c';x.font='42px monospace';x.fillText('SIGNAL RIG',64,93);x.fillStyle='#aeb695';x.font='16px monospace';x.textAlign='right';x.fillText('PHOTO OBJECT / 001',1136,90);x.textAlign='left';
 if(renderer){const oldSize=renderer.getSize(new Vector2()),oldRatio=renderer.getPixelRatio(),oldAspect=camera.aspect,oldPosition=camera.position.clone();try{renderer.setPixelRatio(1);renderer.setSize(1200,1290,false);camera.aspect=1200/1290;const length=oldPosition.length();const size=new Box3().setFromObject(rig).getSize(new Vector3());const distance=Math.max(size.y/(2*Math.tan(Math.PI*40/360)),size.x/(2*Math.tan(Math.PI*40/360)*camera.aspect))*1.1+size.z*.35;camera.position.multiplyScalar(distance/length);camera.updateProjectionMatrix();draw();x.drawImage(renderer.domElement,0,145,1200,1290);}finally{camera.position.copy(oldPosition);camera.aspect=oldAspect;camera.updateProjectionMatrix();renderer.setPixelRatio(oldRatio);renderer.setSize(oldSize.x,oldSize.y,false);draw();}}
 else{images.forEach((im,i)=>{const col=i%3,row=Math.floor(i/3);const p=canvasFor(i,im);x.drawImage(p,90+col*350,210+row*380,300,330);});}
 x.strokeStyle='rgba(249,255,76,.2)';x.beginPath();x.moveTo(64,1460);x.lineTo(1136,1460);x.stroke();x.fillStyle='#aeb695';x.font='18px monospace';x.fillText('08 CHANNELS / YOUR PERSONAL FREQUENCY',64,1510);x.font='14px monospace';x.fillText('A SMALL COLLECTION OF THINGS YOU SEE.',64,1545);return c.toDataURL('image/png');
}
function openOutput(){if(busy)return false;if(!pool.length){announce('先放入至少一张照片，再生成你的装置');choose(0);return false;}try{outputData=poster();$('output-image').src=outputData;previousFocus=document.activeElement;$('output').hidden=false;document.body.style.overflow='hidden';$('save-status').textContent='';$('close-output').focus();return true;}catch(e){announce('图片生成失败，请减少照片大小后重试');return false;}}
function closeOutput(){$('output').hidden=true;document.body.style.overflow='';if(previousFocus)previousFocus.focus();}
async function save(){if(busy)return;if(!outputData&&!openOutput())return;const mini=window.xhs&&window.xhs.miniTool;if(!mini||typeof mini.saveImageToPhotosAlbum!=='function'){$('output').hidden=false;$('save-status').textContent='浏览器预览：右键或长按图片保存。小红书内点击此按钮会保存到相册。';return;}busyState(true);$('save-status').textContent='正在保存…';try{await saveImage(outputData,mini);$('save-status').textContent='已保存到相册';announce('装置图片已保存到相册');}catch(e){$('save-status').textContent='未保存成功，请检查相册权限后重试。你的照片仍在。';}finally{busyState(false);}}
$('build').addEventListener('click',openOutput);$('save').addEventListener('click',()=>{if(openOutput())save();});$('save-output').addEventListener('click',save);$('close-output').addEventListener('click',closeOutput);$('edit').addEventListener('click',closeOutput);
document.addEventListener('keydown',e=>{if($('output').hidden)return;if(e.key==='Escape')closeOutput();if(e.key==='Tab'){const focus=[$('close-output'),$('edit'),$('save-output')].filter(x=>!x.disabled),first=focus[0],last=focus[focus.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
init();
